In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('DataAirForce.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25)
print(X_train)
print(y_train)
print(X_test)
print(y_test)


[[ 1.0750e+04  1.7900e+02  1.0000e+01 ... -1.6670e+01  6.0000e-01
  -2.7000e-01]
 [ 1.3100e+04  2.6200e+02  3.0000e+00 ...  0.0000e+00 -2.2000e-01
  -3.3000e-01]
 [ 6.9750e+03  2.1500e+02  1.6900e+02 ...  3.0560e+01  1.8900e+00
  -1.1000e-01]
 ...
 [ 2.0025e+04  2.1400e+02  4.6000e+01 ...  0.0000e+00 -2.1700e+00
  -3.3300e+00]
 [ 9.1250e+03  1.2600e+02  8.1000e+01 ...  0.0000e+00 -4.6700e+00
   4.4000e-01]
 [ 1.3075e+04  2.7900e+02  3.6000e+01 ...  0.0000e+00 -8.7000e-01
  -3.9000e-01]]
[5 5 4 ... 3 3 5]
[[ 2.7025e+04  4.0900e+02  4.4000e+01 ...  2.6000e-01  2.6000e-01
  -9.0000e-02]
 [ 6.9750e+03  1.8900e+02  7.1000e+01 ...  0.0000e+00  2.8900e+00
   3.3000e-01]
 [ 2.0000e+04  2.2400e+02  4.9000e+01 ... -2.7130e+01  1.0000e-02
  -4.0000e-02]
 ...
 [ 6.9750e+03  1.3600e+02  1.1800e+02 ...  3.8330e+01 -2.0000e-02
  -4.0000e-02]
 [ 3.9950e+04  3.5600e+02  4.8000e+01 ...  0.0000e+00  1.0000e-02
  -1.0000e-02]
 [ 9.1500e+03  1.2000e+02  1.1100e+02 ...  0.0000e+00  4.2200e+00
  -7.8000e-01]

In [4]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train)
print(X_test)

[[-0.33209992 -0.54586929 -1.51720075 ... -0.73801661  0.41472212
  -0.36412595]
 [-0.07359004  0.56299779 -1.64749814 ...  0.03554637 -0.14115718
  -0.44827464]
 [-0.74736581 -0.06491489  1.44241148 ...  1.45366783  1.28921517
  -0.13972947]
 ...
 [ 0.68818911 -0.07827474 -0.84709987 ...  0.03554637 -1.46306527
  -4.65570876]
 [-0.51085676 -1.25394105 -0.1956129  ...  0.03554637 -3.15781924
   0.63163346]
 [-0.07634014  0.79011515 -1.033239   ...  0.03554637 -0.58179321
  -0.53242332]]
[[ 1.45821856e+00  2.52689493e+00 -8.84327694e-01 ...  4.76115418e-02
   1.84235585e-01 -1.11679906e-01]
 [-7.47365810e-01 -4.12270849e-01 -3.81752032e-01 ...  3.55463724e-02
   1.96711676e+00  4.77360872e-01]
 [ 6.85439000e-01  5.53237062e-02 -7.91258127e-01 ... -1.22340766e+00
   1.47601883e-02 -4.15560036e-02]
 ...
 [-7.47365810e-01 -1.12034260e+00  4.93101900e-01 ...  1.81423078e+00
  -5.57685932e-03 -4.15560036e-02]
 [ 2.88002295e+00  1.81882317e+00 -8.09872040e-01 ...  3.55463724e-02
   1.47601883

In [5]:
#LOGISTIC REGRESSION
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [6]:
y_pred = classifier.predict(X_test)

In [7]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[193  69  47  25  58]
 [  0 381 304  25  34]
 [  1 267 716  64  34]
 [ 64  73  65 139  30]
 [ 64  38  95  50 159]]


0.5302170283806343

In [8]:
#KNN (k-nearest-neighbour)
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)


KNeighborsClassifier()

In [9]:
y_pred = classifier.predict(X_test)

In [10]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[371   5   6   5   5]
 [  6 711  25   2   0]
 [  5  81 960  14  22]
 [ 16  17  26 295  17]
 [  8  20  28  11 339]]


0.8934891485809683

In [11]:
#SVM(support vector machine)
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear')
classifier.fit(X_train, y_train)


SVC(kernel='linear')

In [12]:
y_pred = classifier.predict(X_test)

In [13]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[224  67  29  45  27]
 [  2 564 126  33  19]
 [  2 407 579  64  30]
 [ 56  74  63 164  14]
 [ 58  78  54  52 164]]


0.5659432387312187

In [14]:
#NAIVE BAYES
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [15]:
y_pred = classifier.predict(X_test)

In [16]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[208  73  43  36  32]
 [  4 560 142  15  23]
 [ 29 341 600  20  92]
 [ 49  74  97  91  60]
 [ 47 102  77   0 180]]


0.547245409015025

In [17]:
#DECISION TREE
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [18]:
y_pred = classifier.predict(X_test)

In [19]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 368    8    4    6    6]
 [   2  713   20    4    5]
 [   4   40 1011    8   19]
 [  13    6   15  331    6]
 [   7    4   14   10  371]]


0.9328881469115192

In [20]:
#RANDOM FOREST
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [21]:
y_pred = classifier.predict(X_test)

In [22]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 375    1    2    8    6]
 [   3  734    5    2    0]
 [   3   17 1049    8    5]
 [   8    4   16  339    4]
 [   2    6   24    5  369]]


0.9569282136894824